<?php

/**
 * @file
 * Contains sliderwidget.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sliderwidget_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sliderwidget module.
    case 'help.page.sliderwidget':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Slider UI field') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sliderwidget_theme() {
  return [
    'slider_sliderelement' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for slider item templates.
 *
 * Default template: slider-sliderelement.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function sliderwidget_preprocess_slider_sliderelement(array &$variables) {
  $variables['slider'] = $variables['elements']['slider'];
}
